/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package akkaPlayground;

import akka.actor.typed.ActorSystem;
import kamon.Kamon;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

//   -> / LocalActorRefProvider$$anon$2 class akka.actor.LocalActorRefProvider$Guardian status=0 2 children
//    ⌊-> system LocalActorRef class akka.actor.LocalActorRefProvider$SystemGuardian status=0 4 children
//    |   ⌊-> deadLetterListener RepointableActorRef class akka.event.DeadLetterListener status=0 no children
//    |   ⌊-> eventStreamUnsubscriber-1 RepointableActorRef class akka.event.EventStreamUnsubscriber status=0 no children
//    |   ⌊-> localReceptionist RepointableActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=0 no children
//    |   ⌊-> log1-Slf4jLogger RepointableActorRef class akka.event.slf4j.Slf4jLogger status=0 no children
//    ⌊-> user LocalActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=2 4 children
//        ⌊-> speaker-1 LocalActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=2 no children
//        ⌊-> speaker-2 LocalActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=2 no children
//        ⌊-> speaker-3 LocalActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=2 no children
//        ⌊-> speaker-4 LocalActorRef class akka.actor.typed.internal.adapter.ActorAdapter status=2 no children
    public static void main(String[] args) {
        Kamon.init();
        ActorSystem<?> system = ActorSystem.create(RootActor.create(), "local");

        // system.logConfiguration();
    }
}
